[package]
name = "starkvote"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.5.4"

[dev-dependencies]
starknet = ">=2.5.4"

[[target.starknet-contract]]
# This tells Scarb that your project builds Starknet contracts
